/* main.c generated by valac 0.56.3, the Vala compiler
 * generated from main.vala, do not modify */

/*https://zhuanlan.zhihu.com/p/471057010*/
/*  在GNOME3平台上，需要以下命令来编译这一示例:*/
/*  valac --pkg gtk+-3.0 hellogtk.vala*/
/*  简陋的Vala*/

#include <glib.h>
#include <glib-object.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_SAMPLE (sample_get_type ())
#define SAMPLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SAMPLE, Sample))
#define SAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SAMPLE, SampleClass))
#define IS_SAMPLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SAMPLE))
#define IS_SAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SAMPLE))
#define SAMPLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SAMPLE, SampleClass))

typedef struct _Sample Sample;
typedef struct _SampleClass SampleClass;
typedef struct _SamplePrivate SamplePrivate;
enum  {
	SAMPLE_0_PROPERTY,
	SAMPLE_NUM_PROPERTIES
};
static GParamSpec* sample_properties[SAMPLE_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Sample {
	GObject parent_instance;
	SamplePrivate * priv;
};

struct _SampleClass {
	GObjectClass parent_class;
};

static gpointer sample_parent_class = NULL;

static void _vala_main (void);
VALA_EXTERN GType sample_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Sample, g_object_unref)
static void sample_run (Sample* self);
static void sample_main2 (gchar** args,
                   gint args_length1);
VALA_EXTERN Sample* sample_new (void);
VALA_EXTERN Sample* sample_construct (GType object_type);
static GType sample_get_type_once (void);

static void
_vala_main (void)
{
	g_print ("Hello World\n");
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

static void
sample_run (Sample* self)
{
	FILE* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Hello World\n");
}

static void
sample_main2 (gchar** args,
              gint args_length1)
{
	Sample* sample = NULL;
	Sample* _tmp0_;
	_tmp0_ = sample_new ();
	sample = _tmp0_;
	sample_run (sample);
	_g_object_unref0 (sample);
}

Sample*
sample_construct (GType object_type)
{
	Sample * self = NULL;
	self = (Sample*) g_object_new (object_type, NULL);
	return self;
}

Sample*
sample_new (void)
{
	return sample_construct (TYPE_SAMPLE);
}

static void
sample_class_init (SampleClass * klass,
                   gpointer klass_data)
{
	sample_parent_class = g_type_class_peek_parent (klass);
}

static void
sample_instance_init (Sample * self,
                      gpointer klass)
{
}

static GType
sample_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (SampleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sample_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Sample), 0, (GInstanceInitFunc) sample_instance_init, NULL };
	GType sample_type_id;
	sample_type_id = g_type_register_static (G_TYPE_OBJECT, "Sample", &g_define_type_info, 0);
	return sample_type_id;
}

GType
sample_get_type (void)
{
	static volatile gsize sample_type_id__once = 0;
	if (g_once_init_enter (&sample_type_id__once)) {
		GType sample_type_id;
		sample_type_id = sample_get_type_once ();
		g_once_init_leave (&sample_type_id__once, sample_type_id);
	}
	return sample_type_id__once;
}

